### PR TITLE
Changed handling of execStream function.

### PR DESCRIPTION
**Pull request by mattoz0**
- Changed Readable stream to a Transform stream (still implements Readable stream so docs are fine).
- Bound events directly to the stream so that the stream end can be detected by consumers.
- removed event handlers and instead piped the results from stdout.

### CODE REVIEW

**Comment by mattoz0** [comment]
Inspiration for the handling of this function is borrowed from node-ytdl-core. I guess the philosophy is pass all error events to the user to handle, and just pipe the data directly from the source to the consumer.

**Comment by mattoz0** [comment]
tests are adjusted to fit and now its over to you!

**Comment by ghjbnm** [comment]
I don't see the reason why a transform stream should be used.
Also afaik child_process doesn't emit most of these events:
https://nodejs.org/api/child_process.html

**Comment by ghjbnm** [comment]
I don't think I want to make a passthrough from the process events to the stream.

**Comment by mattoz0** [comment]
I updated the events to match those emitted by ChildProcess (good catch btw). I had just taken the exact events bound by node-ytdl-core and didn't check they were the same (they used miniget so the events match miniget).

In regards to the transform stream i decided it was a better fit. A Transform stream is a full-duplex stream which implements both the Readable interface and the Writeable interface. Since what we are trying to do is pipe from stdout to a user defined consumer. I decided against a Duplex stream purely to avoid implementing both read/write functions.

**Comment by mattoz0** [comment]
All good ill maintain a seperate fork that works for music bots.

**Pull request closed without merging**
